#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "trivabble"
name = "Trivabble"
description.en = "Scrabble® game free play not enforcing rules"
description.fr = "Scrabble® en jeu libre, à l'utilisateur d'appliquer les règles"

version = "2025.10.31~ynh1"

maintainers = ["Philippe Lhardy"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://trivabble.org/"
code = "https://git.jakse.fr/trivabble/trivabble"

[integration]
architectures = "all"
yunohost = ">= 12.1.17"
helpers_version = "2.1"
multi_instance = false

ldap = false
sso = false

disk = "250M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/trivabble"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    url = "https://git.jakse.fr/trivabble/trivabble/archive/prod-v20251031.tar.gz"
    sha256 = "18c5feff41539f9f2f0c4a2736b4be28196db7ccb391207ba916ee83f5f4b93e"

    [resources.system_user]
    
    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    
    [resources.apt]
    packages = ["rsync"]

    [resources.nodejs]
    version = "22"
