#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

setting_source_files

# Set right permissions for curl install
chown -R $app $install_dir

# TWEAK trivabble client configuration
ynh_script_progression "Create client configuration for this app path $path"

cat <<EOF >$install_dir/public/config.js
window.TrivabbleConf = {
    APP_PATH: "$path"
}
EOF

# Set permissions to app files
chown -R $app:$app $install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Trivabble game web server service" --log="/var/log/$app/$app.log"

mkdir -p "/var/log/$app"
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
